# Created by: R. Christian McDonald <cmcdonald@netgate.com>

PORTNAME=	zephir_parser
DISTVERSION=	1.5.0
CATEGORIES=	textproc

MAINTAINER=	cmcdonald@netgate.com
COMMENT=	Zephir Parser delivered as a C extension for the PHP language

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		php:pecl

TEST_TARGET=	test

.include <bsd.port.mk>
