PORTNAME=	cligen
PORTVERSION=	5.5.0
CATEGORIES=	devel

MAINTAINER=	dcornejo@netgate.com
COMMENT=	Command-line interface generator

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		bison:alias compiler:c11 gmake

USE_GITHUB=	yes
GH_ACCOUNT=	clicon

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
